name: JumpPad
version: '1.0.0'
main: net.xtb.jumpPad.JumpPad
api-version: '1.21'
commands:
  jumppad:
    permission: jumppad.manage

permissions:
  jumppad.manage:
    default: op
  jumppad.use:
    default: true